// Згенеровано make_cssref.py з hominka/cssui/catalog.py — не правити руками.
#include "ui/cssref.h"

namespace hominka {

namespace {

const std::vector<CssRecipe> kRecipes = {
    {"Крупніший текст",
     "Найчастіша правка: чат у кадрі дрібний.",
     "body { font-size: 26px; }"},
    {"Компактні рядки",
     "Більше повідомлень в тій самій висоті.",
     "#list { gap: 2px; }\n.m { line-height: 1.15; }"},
    {"Підкладка під рядком",
     "Читається на будь-якій картинці, не лише на темній.",
     ".m {\n  background: rgba(0,0,0,.5);\n  padding: 3px 8px;\n  border-radius: 10px;\n}"},
    {"Смуга кольору площадки",
     "Видно з одного погляду, звідки прийшло повідомлення.",
     ".m[data-platform=\"twitch\"] { border-left: 3px solid #9146ff; padding-left: 6px; }\n.m[data-platform=\"kick\"]   { border-left: 3px solid #53fc18; padding-left: 6px; }\n.m[data-platform=\"youtube\"]{ border-left: 3px solid #ff0033; padding-left: 6px; }"},
    {"Прибрати значки автора",
     "MOD/VIP/SUB зникають, лишається нік.",
     ".b { display: none; }"},
    {"Прибрати іконки площадок",
     "Коли площадка одна, значок лише займає місце.",
     ".ico { display: none; }"},
    {"Свій колір ніків",
     "Площадка ставить свій колір інлайном — тому !important.",
     ".n { color: #ffd166 !important; font-weight: 800; }"},
    {"Донати помітніше",
     "Гроші не мають губитися серед звичайних рядків.",
     ".m[data-kind=\"money\"] {\n  background: rgba(251,191,36,.30);\n  border-radius: 10px;\n}\n.money { font-size: .9em; }"},
    {"Системні тихіше",
     "Рейди й підписки не перебивають розмову.",
     ".sys { opacity: .55; font-size: .78em; }"},
    {"Без анімації появи",
     "Якщо рух у кадрі відволікає.",
     ".m { animation: none; }"},
    {"Товстіший контур тексту",
     "Читається навіть на світлій грі.",
     "body { text-shadow: 0 0 4px #000, 0 0 8px #000, 0 2px 3px #000; }"},
    {"Більші емоути",
     "Емоути на всю висоту рядка.",
     ".em { height: 2em; }"},
    {"Сховати чат сайту",
     "Лишити тільки площадки.",
     ".m[data-platform=\"site\"] { display: none; }"},
    {"Яскравіші звертання",
     "Коли звертаються до вас — має кидатися в очі.",
     ".at { background: #f59e0b; color: #111; border-radius: .3em; }"},
    {"Рядки з відступом зліва",
     "Коли хочеться відсунути чат від краю.",
     "#list { inset: 8px 8px 8px 24px; }"},
    {"Все праворуч",
     "Чат притиснутий до правого краю вікна.",
     "#list { align-items: flex-end; text-align: right; }"},
    {"Рейд і підписки окремими кольорами",
     "Щоб не загубити подію в потоці розмови.",
     ".m[data-event=\"raid\"] { background: rgba(168,85,247,.35); padding: 3px 8px;\n                        border-radius: 8px; }\n.m[data-event=\"sub\"]  { background: rgba(34,197,94,.28); padding: 2px 8px;\n                        border-radius: 8px; }\n.m[data-event=\"gift\"] { background: rgba(236,72,153,.28); padding: 2px 8px;\n                        border-radius: 8px; }"},
    {"Без двокрапки після ніка",
     "Потрібне, коли нік переставили в кінець рядка.",
     ".n::after { content: ''; }"},
    {"Текст із нового рядка",
     "Нік зверху, повідомлення під ним.",
     ".t { display: block; }"},
    {"Сховати службові рядки",
     "Зміни режиму чату й витрачені бали.",
     ".m[data-event=\"mode\"], .m[data-event=\"points\"] { display: none; }"},
};

const std::vector<CssSelector> kSelectors = {
    {"#list",
     "Уся стрічка",
     "Колонка з повідомленнями: відступи від країв, напрямок і проміжок між рядками.",
     "#list {\n  inset: 16px;      /* відступи від країв вікна */\n  gap: 10px;        /* проміжок між рядками */\n}"},
    {".m",
     "Одне повідомлення",
     "Обгортка кожного рядка: фон, рамка, скруглення, поля.",
     ".m {\n  background: rgba(0,0,0,.45);\n  padding: 3px 8px;\n  border-radius: 10px;\n}"},
    {".m[data-platform=\"twitch\"]",
     "Тільки з Twitch",
     "Те саме, але лише для Twitch. Так само: kick, youtube, site (чат сайту).",
     ".m[data-platform=\"twitch\"] {\n  border-left: 3px solid #9146ff;\n  padding-left: 6px;\n}"},
    {".m[data-platform=\"kick\"]",
     "Тільки з Kick",
     "Повідомлення, що прийшли з Kick.",
     ".m[data-platform=\"kick\"] {\n  border-left: 3px solid #53fc18;\n  padding-left: 6px;\n}"},
    {".m[data-platform=\"youtube\"]",
     "Тільки з YouTube",
     "Повідомлення, що прийшли з YouTube.",
     ".m[data-platform=\"youtube\"] {\n  border-left: 3px solid #ff0033;\n  padding-left: 6px;\n}"},
    {".m[data-kind=\"money\"]",
     "Донат / Super Chat",
     "Рядок із грошима. Поряд працює клас .paid — типове оформлення донату.",
     ".m[data-kind=\"money\"] {\n  background: rgba(251,191,36,.28);\n  border-radius: 10px;\n}"},
    {".m[data-kind=\"system\"]",
     "Будь-яка подія площадки",
     "Рейди, підписки, оголошення — усе разом. Нижче кожна окремо.",
     ".m[data-kind=\"system\"] {\n  opacity: .7;\n}"},
    {".m[data-event=\"raid\"]",
     "Рейд",
     "До вас привели глядачів. Окремий вигляд — щоб не проґавити.",
     ".m[data-event=\"raid\"] {\n  background: rgba(168,85,247,.35);\n  border-left: 4px solid #a855f7;\n  padding: 3px 8px;\n}"},
    {".m[data-event=\"sub\"]",
     "Підписка",
     "Нова підписка або поновлення. Спонсорство YouTube — теж сюди.",
     ".m[data-event=\"sub\"] {\n  background: rgba(34,197,94,.28);\n  border-radius: 8px;\n  padding: 2px 8px;\n}"},
    {".m[data-event=\"gift\"]",
     "Подарована підписка",
     "Хтось подарував підписку іншим — привід окремий від власної підписки.",
     ".m[data-event=\"gift\"] {\n  background: rgba(236,72,153,.28);\n  border-radius: 8px;\n  padding: 2px 8px;\n}"},
    {".m[data-event=\"announce\"]",
     "Оголошення",
     "Оголошення ведучого чи модератора (Twitch /announce).",
     ".m[data-event=\"announce\"] {\n  border-left: 4px solid #38bdf8;\n  padding-left: 8px;\n}"},
    {".m[data-event=\"pin\"]",
     "Закріплене",
     "Повідомлення, закріплене в чаті площадки.",
     ".m[data-event=\"pin\"] {\n  outline: 1px solid #fbbf24;\n  border-radius: 8px;\n}"},
    {".m[data-event=\"points\"]",
     "Бали каналу",
     "Витрачені бали каналу (Kick, Twitch-нагороди).",
     ".m[data-event=\"points\"] {\n  opacity: .6;\n}"},
    {".m[data-event=\"bits\"]",
     "Біти Twitch",
     "Повідомлення з бітами. Поряд працює .money — сама плашка з сумою.",
     ".m[data-event=\"bits\"] {\n  background: rgba(145,70,255,.25);\n}"},
    {".m[data-event=\"superchat\"]",
     "Super Chat",
     "Платне повідомлення YouTube.",
     ".m[data-event=\"superchat\"] {\n  background: rgba(255,0,51,.22);\n}"},
    {".m[data-event=\"mode\"]",
     "Зміна режиму чату",
     "«Тільки для підписників» і подібні службові рядки.",
     ".m[data-event=\"mode\"] {\n  display: none;\n}"},
    {".ico",
     "Значок площадки",
     "Логотип Twitch / Kick / YouTube перед рядком. Розмір в em — тягнеться за текстом.",
     ".ico {\n  width: 1.2em;\n  height: 1.2em;\n}"},
    {".b",
     "Значок автора",
     "MOD, VIP, SUB, HOST і решта текстових плашок біля ніка.",
     ".b {\n  border-radius: 999px;\n  font-size: .5em;\n}"},
    {".bi",
     "Іконка значка",
     "Справжня картинка значка (Twitch/Kick/YouTube) на місці плашки, коли вона є.",
     ".bi {\n  height: 1.4em;\n}"},
    {".n",
     "Нік автора",
     "Колір приходить із площадки і стоїть інлайном — свій треба ставити з !important.",
     ".n {\n  color: #ffd166 !important;\n  font-weight: 800;\n}"},
    {".money",
     "Сума донату",
     "Жовта плашка з сумою.",
     ".money {\n  background: #22c55e;\n  color: #052e16;\n}"},
    {".re",
     "Кому відповідають",
     "Рядок «↳ нік» перед текстом відповіді.",
     ".re {\n  color: #c4b5fd;\n  font-size: .75em;\n}"},
    {".t",
     "Текст повідомлення",
     "Сам текст (без ніка й плашок). Раніше стилізувати його окремо було нічим.",
     ".t {\n  font-weight: 500;\n  color: #f4f4f5;\n}"},
    {".n::after",
     "Двокрапка після ніка",
     "Малюється стилем, а не текстом — тому її можна прибрати або замінити.",
     ".n::after {\n  content: '';\n}"},
    {".em",
     "Емоут",
     "Картинка емоута всередині тексту.",
     ".em {\n  height: 2em;\n}"},
    {".at",
     "Звертання @нік",
     "Підсвічене звертання в тексті повідомлення.",
     ".at {\n  background: #f59e0b;\n  color: #111;\n}"},
    {".sys",
     "Текст системного",
     "Курсив рейдів, підписок і подібного.",
     ".sys {\n  font-style: normal;\n  color: #c4b5fd;\n}"},
    {".paid",
     "Оформлення донату",
     "Жовта смуга ліворуч і підкладка для повідомлень із грошима.",
     ".paid {\n  border-left-color: #22c55e;\n}"},
    {"body",
     "Загальні налаштування",
     "Шрифт, базовий кегль, колір тексту, тінь під текстом.",
     "body {\n  font-size: 26px;\n  text-shadow: 0 0 4px #000, 0 2px 3px #000;\n}"},
    {"Поява рядка",
     "Її задає програма, не CSS",
     "Новий рядок виїжджає знизу й проявляється — це малює сама програма. CSS-анімації (@keyframes, transition) рушій не програє, тож змінити можна вигляд рядка, а не його появу.",
     ".m {\n  /* появу малює програма; тут — звичайні стилі рядка */\n}"},
};

}  // namespace

const std::vector<CssRecipe>& css_recipes() { return kRecipes; }
const std::vector<CssSelector>& css_selectors() { return kSelectors; }

}  // namespace hominka
